import type { FormFieldSchema } from './formSchemas'

const fieldLabels: Record<string, string> = {
  abilityToDoBetter: 'Возможность работать лучше',
  achievements: 'Достижения',
  additionalEducation: 'Дополнительное образование',
  additionalExamScore: 'Баллы за дополнительный экзамен',
  additionalExamSubject: 'Дополнительный экзамен',
  additionalSkills: 'Дополнительные навыки',
  ageYears: 'Возраст',
  averageScore: 'Средняя оценка',
  birthDate: 'Дата рождения',
  candidateTrack: 'Трек кандидата',
  careerGoals: 'Карьерные цели',
  changedCitizenship: 'Менялось гражданство',
  citizenship: 'Гражданство',
  comfort: 'Комфорт',
  comfortScore: 'Оценка комфорта',
  comment: 'Комментарий',
  comments: 'Комментарии',
  communication: 'Коммуникация',
  companyRecommendation: 'Рекомендация компании',
  contactFullName: 'ФИО контактного лица',
  createdAt: 'Дата создания',
  course: 'Курс',
  curator: 'Куратор',
  curatorFeedback: 'Отзыв куратора',
  currentWorkStatus: 'Текущий рабочий статус',
  databaseSkills: 'Навыки работы с БД',
  degree: 'Уровень образования',
  department: 'Кафедра',
  desiredPositions: 'Желаемые позиции',
  detractorsComment: 'Комментарий критиков',
  devOpsSkills: 'DevOps-навыки',
  development: 'Развитие',
  developmentFor: 'Направление развития',
  discipline: 'Дисциплина',
  durationRating: 'Оценка длительности',
  educationInstitution: 'Учебное заведение',
  educationInstitutionOther: 'Другое учебное заведение',
  educationalInterests: 'Образовательные интересы',
  email: 'Email',
  employeeFullName: 'ФИО сотрудника',
  expectationOfEmployer: 'Ожидания работодателя',
  expectationsMatch: 'Соответствие ожиданиям',
  experienceDays: 'Опыт, дней',
  faculty: 'Факультет',
  feedbackDate: 'Дата отзыва',
  filledAt: 'Дата заполнения',
  foreignLanguages: 'Иностранные языки',
  friendAtWork: 'Друг на работе',
  fullName: 'ФИО',
  growthAreas: 'Зоны роста',
  growthAtWork: 'Рост на работе',
  hasJob: 'Есть работа',
  hasRelativesAbroad: 'Есть родственники за границей',
  hobbies: 'Хобби',
  hostRating: 'Оценка ведущего',
  idealEmployer: 'Идеальный работодатель',
  idealWorkplace: 'Идеальное место работы',
  instructionClarity: 'Понятность инструкций',
  internalMeetings: 'Внутренние встречи',
  interviewResult: 'Результат интервью',
  jobContentScore: 'Оценка содержания работы',
  knowledgeApplication: 'Применение знаний',
  knowledgeLevels: 'Уровни знаний',
  leadership: 'Лидерство',
  logic: 'Логика подачи',
  loyalty: 'Лояльность',
  managerCare: 'Забота руководителя',
  materialPerception: 'Восприятие материала',
  materialVolume: 'Объём материала',
  mathematicsExamScore: 'Баллы ЕГЭ по математике',
  meetingDate: 'Дата встречи',
  meetingDynamics: 'Динамика встречи',
  meetingOverall: 'Общая оценка встречи',
  mentor: 'Ментор',
  mentorComment: 'Комментарий ментора',
  mentoringDays: 'Дней менторинга',
  militaryRegistration: 'Воинский учёт',
  missionAndGoal: 'Миссия и цели',
  motivationOfOthers: 'Мотивация других',
  name: 'Название',
  newKnowledge: 'Новые знания',
  organizationalSkills: 'Организационные навыки',
  otherContacts: 'Другие контактные лица',
  pace: 'Темп',
  participationGoals: 'Цели участия',
  passedExam: 'Сдавал экзамен',
  passivelySatisfiedComment: 'Комментарий нейтральных',
  personalDataConsent: 'Согласие на обработку данных',
  phone: 'Телефон',
  photo: 'Фото',
  pointOfView: 'Учёт мнения',
  position: 'Позиция',
  practicalSkillsQuality: 'Качество практических навыков',
  practiceHistory: 'История практики',
  professions: 'Профессии',
  programmingSkills: 'Навыки программирования',
  projectTypes: 'Типы проектов',
  projects: 'Проекты',
  projectsInCenter: 'Проекты в центре',
  promotersComment: 'Комментарий сторонников',
  qualityWork: 'Качество работы',
  questionnaireProjects: 'Проекты из анкеты',
  rating: 'Рейтинг',
  recognitionAndPraise: 'Признание и похвала',
  recommendation: 'Рекомендация',
  referrerFullName: 'ФИО рекомендателя',
  registrationRegion: 'Регион регистрации',
  relationship: 'Степень родства',
  requests: 'Запросы',
  roles: 'Роли',
  russianExamScore: 'Баллы ЕГЭ по русскому',
  safetyScore: 'Оценка безопасности',
  salaryScore: 'Оценка зарплаты',
  saturation: 'Насыщенность',
  selfMotivation: 'Самомотивация',
  skills: 'Навыки',
  source: 'Источник',
  specialty: 'Специальность',
  status: 'Статус',
  submissionNumber: 'Номер заявки',
  surveyDate: 'Дата опроса',
  systemAdministrationSkills: 'Навыки системного администрирования',
  talkAboutSuccesses: 'Обсуждение успехов',
  targetEducation: 'Целевое обучение',
  technicalInterviewDates: 'Даты технических интервью',
  technicalInterviewResults: 'Результаты технических интервью',
  telegram: 'Telegram',
  telegramUrl: 'Ссылка Telegram',
  temporaryRegistration: 'Временная регистрация',
  testingSkills: 'Навыки тестирования',
  traineeFullName: 'ФИО стажёра',
  theoryHistory: 'История теории',
  thirdExamScore: 'Баллы за третий экзамен',
  thirdExamSubject: 'Третий экзамен',
  toolsAndMaterial: 'Инструменты и материалы',
  topicImportance: 'Важность темы',
  topicRelevance: 'Актуальность темы',
  totalExamScore: 'Сумма баллов ЕГЭ',
  trainer: 'Тренер',
  trainerNameFormula: 'ФИО тренера',
  trainerWork: 'Работа тренера',
  travelAvailability: 'Готовность к командировкам',
  type: 'Тип',
  universityAverageScore: 'Средний балл в вузе',
  universityChoicePrinciple: 'Принцип выбора вуза',
  webDevelopmentSkills: 'Навыки веб-разработки',
  workOrInternship: 'Работа или стажировка',
  workPlanHours: 'План рабочих часов',
  workingConditionsScore: 'Оценка условий труда',
}

const feedbackLabels = {
  feedbackDate: 'Дата встречи',
  averageScore: 'Ср.значение',
  meetingOverall: '1. Встреча в целом',
  hostRating: '2. Ведущий',
  topicRelevance: '3. Соответствие тематики',
  durationRating: '4. Продолжительность',
  instructionClarity: '5. Четкость и ясность инструкций',
  meetingDynamics: '6. Яркость и динамичность встречи',
  practicalSkillsQuality: '7. Качество полученных вами практических навыков',
  expectationsMatch: '8. Степень оправдания',
  recommendation: '9. Рекомендация',
  comment: 'Ваши комментарии',
}

const eventApplicationLabels = {
  fullName: 'ФИО',
  roles: 'Роль',
  meetingDate: 'Дата встречи',
  type: 'Тип',
  comment: 'Комментарий',
}

const threeSixtyLabels = {
  averageScore: 'Оценка',
  curator: 'Куратор',
  communication: '1. Коммуникация',
  organizationalSkills: '2. Организаторские способности',
  discipline: '3. Дисциплинированность',
  leadership: '4. Лидерство',
  selfMotivation: '5. Самомотивация',
  loyalty: '6. Лояльность',
  motivationOfOthers: '7. Мотивация других',
  comment: 'Комментарий',
}

const resourceFieldLabels: Record<string, Record<string, string>> = {
  'welcome-training-feedback': {
    trainerNameFormula: 'ФИО тренера.',
    trainer: 'ФИО тренера',
    averageScore: 'Ср.оценка',
    filledAt: 'Дата заполнения.',
    topicImportance: 'Важность темы',
    newKnowledge: 'Новые знания',
    knowledgeApplication: 'Применение знаний',
    saturation: 'Насыщенность',
    logic: 'Логичность',
    materialVolume: 'Объем материала',
    comfort: 'Комфортность',
    materialPerception: 'Восприимчивость материала',
    pace: 'Темп',
    trainerWork: 'Работа тренера',
    comments: 'Комментарии',
  },
  'battle-of-opinions-feedback': feedbackLabels,
  'negotiation-duel-feedback': feedbackLabels,
  'battle-of-opinions-applications': eventApplicationLabels,
  'negotiation-duel-applications': eventApplicationLabels,
  'trainee-three-sixty-reviews': threeSixtyLabels,
  'curator-three-sixty-reviews': {
    averageScore: 'Оценка',
    curator: 'Куратор',
    communication: '1. Коммуникация',
    discipline: '2. Дисциплинированность',
    selfMotivation: '3. Самомотивация',
    loyalty: '4. Лояльность',
    motivationOfOthers: '5. Мотивация других',
    comment: 'Комментарий',
  },
  'leadership-three-sixty-reviews': threeSixtyLabels,
  'engagement-surveys': {
    filledAt: 'Дата заполнения',
    expectationOfEmployer: '1. Ожидание работодателя',
    toolsAndMaterial: '2. Инструменты/Материал',
    abilityToDoBetter: '3. Возможность делать лучше',
    recognitionAndPraise: '4. Признание/Похвала',
    managerCare: '5. Забота руководителя',
    development: '6. Развитие',
    pointOfView: '7. Точка зрения',
    missionAndGoal: '8. Миссия и цель',
    qualityWork: '9. Качественная работа',
    friendAtWork: '10. Наличие друга на работе',
    talkAboutSuccesses: '11. Разговор об успехах',
    growthAtWork: '12. Развитие на работе',
  },
  'satisfaction-surveys': {
    surveyDate: 'Дата',
    salaryScore: '1. Оплата труда',
    workingConditionsScore: '2. Условия труда',
    jobContentScore: '3. Содержание труда',
    safetyScore: '4. Безопасность труда',
    comfortScore: '5. Комфорт труда',
  },
  'loyalty-surveys': {
    surveyDate: 'Дата',
    companyRecommendation: 'Рекомендация компании',
    promotersComment: 'Комментарий к оценке (Promoters)',
    passivelySatisfiedComment: 'Комментарий к оценке (Passively Satisfied)',
    detractorsComment: 'Комментарий к оценке (Detractors)',
  },
  'trainee-contacts': {
    contactFullName: 'ФИО контактного лица',
    relationship: 'Степень родства',
    phone: 'Телефон',
    otherContacts: 'Прочие лица и их данные (ФИО-степень родства -телефон)',
    traineeFullName: 'ФИО студента',
    createdAt: 'Дата создания',
  },
  'candidate-questionnaires': {
    fullName: 'ФИО',
    citizenship: 'Гражданство',
    registrationRegion: 'Регион регистрации',
    temporaryRegistration: 'Есть ли временная регистрация',
    hasRelativesAbroad: 'Есть родственники за границей',
    changedCitizenship: 'Менялось гражданство',
    militaryRegistration: 'Воинский учёт',
    hasJob: 'Есть работа',
    targetEducation: 'Целевое обучение',
    travelAvailability: 'Готовность к командировкам',
    phone: 'Телефон',
    email: 'Email',
    telegramUrl: 'Ссылка Telegram (t.me/****)',
    birthDate: 'Дата рождения',
    passedExam: 'Сдача ЕГЭ',
    russianExamScore: 'Баллы ЕГЭ по русскому',
    mathematicsExamScore: 'Баллы ЕГЭ по математике',
    thirdExamSubject: 'ЕГЭ по выбору',
    thirdExamScore: 'Баллы за ЕГЭ по выбору',
    additionalExamSubject: 'Дополнительный экзамен',
    additionalExamScore: 'Баллы за дополнительный экзамен',
    totalExamScore: 'Сумма баллов ЕГЭ',
    educationInstitution: 'Учебное заведение',
    educationInstitutionOther: 'Другое учебное заведение',
    faculty: 'Факультет',
    department: 'Кафедра',
    degree: 'Уровень образования',
    course: 'Курс',
    specialty: 'Специальность (код ОКСО, например 10.03.01)',
    universityAverageScore: 'Средний балл в вузе',
    universityChoicePrinciple: 'Принцип выбора вуза',
    workOrInternship: 'Опыт работы или стажировки',
    foreignLanguages: 'Владение иностранными языками',
    educationalInterests: 'Образовательные интересы',
    projects: 'Проекты',
    additionalEducation: 'Дополнительное образование',
    achievements: 'Достижения',
    skills: 'Навыки',
    growthAreas: 'Зоны роста',
    source: 'Источник',
    referrerFullName: 'ФИО рекомендателя',
    hobbies: 'Хобби',
    idealWorkplace: 'Идеальное место работы',
    idealEmployer: 'Идеальный работодатель',
    professions: 'Профессии',
    personalDataConsent: 'Согласие на обработку данных',
  },
  'freelance-project-catalog': {
    name: 'Наименование проекта',
    requests: 'Запрос',
  },
  'freelance-applications': {
    employeeFullName: 'ФИО сотрудника',
    status: 'СТАТУС',
    roles: 'Роль',
    desiredPositions: 'Желаемая позиция',
    phone: 'Телефон',
    email: 'Email',
    telegram: 'Telegram',
    projectTypes: 'Типы проектов',
    programmingSkills: 'Программирование',
    knowledgeLevels: 'Уровень знаний',
    webDevelopmentSkills: 'Веб-разработка',
    databaseSkills: 'Базы данных',
    systemAdministrationSkills: 'Сист.администрирование',
    devOpsSkills: 'DevOps',
    testingSkills: 'Тестирование',
    additionalSkills: 'Доп.навыки',
    participationGoals: 'Цели участия',
    workPlanHours: 'План, раб/час',
  },
  'resume-profiles': {
    fullName: '1. ФИО',
    status: 'СТАТУС',
    photo: 'Фото',
    position: 'Должность',
    experienceDays: 'Стаж, дн',
    developmentFor: 'Развитие для',
    rating: 'Рейтинг',
    ageYears: 'Возраст, лет',
    currentWorkStatus: 'Текущий рабочий статус',
    interviewResult: 'Результат собеседования',
    internalMeetings: 'Внутренние встречи',
    careerGoals: 'Карьерные цели',
    curator: 'Куратор',
    curatorFeedback: 'ОС куратора',
    technicalInterviewDates: 'Даты тех.собеседования',
    technicalInterviewResults: 'Результаты тех.собеседования',
    mentor: 'Наставник',
    mentoringDays: 'Срок наставничества, дн.',
    mentorComment: 'Комментарий наставника',
    theoryHistory: 'История прохождения теории',
    practiceHistory: 'История прохождения практики',
    candidateTrack: 'Курс кандидата (трек)',
    projectsInCenter: 'Проекты (ЦРТРИС)',
    educationInstitution: 'Наименование уч.заведения',
    degree: 'Ступень',
    course: 'Курс',
    specialty: 'Специальность',
    totalExamScore: 'Итоги  ЕГЭ (по 3-м предметам)',
    faculty: 'Факультет',
    department: 'Кафедра',
    workOrInternship: 'Работа/Стажировка',
    educationalInterests: 'Учебные интересы',
    questionnaireProjects: 'Проекты (анкета)',
    additionalEducation: 'Дополнительное образование',
    achievements: 'Достижения',
    skills: 'Навыки',
    growthAreas: 'Зоны роста',
    professions: 'Профессия',
    travelAvailability: 'Командировки',
  },
}

export function getFieldLabel(field: FormFieldSchema, resource?: string) {
  return (resource && resourceFieldLabels[resource]?.[field.name])
    ?? fieldLabels[field.name]
    ?? field.label
}
