import type { FormFieldSchema } from './formSchemas'

const fieldLabels: Record<string, string> = {
  abilityToDoBetter: 'Возможность работать лучше',
  achievements: 'Достижения',
  additionalEducation: 'Дополнительное образование',
  additionalExamScore: 'Баллы за дополнительный экзамен',
  additionalExamSubject: 'Дополнительный экзамен',
  additionalSkills: 'Дополнительные навыки',
  ageYears: 'Возраст',
  averageScore: 'Средняя оценка',
  birthDate: 'Дата рождения',
  candidateTrack: 'Трек кандидата',
  careerGoals: 'Карьерные цели',
  changedCitizenship: 'Менялось гражданство',
  citizenship: 'Гражданство',
  comfort: 'Комфорт',
  comfortScore: 'Оценка комфорта',
  comment: 'Комментарий',
  comments: 'Комментарии',
  communication: 'Коммуникация',
  companyRecommendation: 'Рекомендация компании',
  course: 'Курс',
  curator: 'Куратор',
  curatorFeedback: 'Отзыв куратора',
  currentWorkStatus: 'Текущий рабочий статус',
  databaseSkills: 'Навыки работы с БД',
  degree: 'Уровень образования',
  department: 'Кафедра',
  desiredPositions: 'Желаемые позиции',
  detractorsComment: 'Комментарий критиков',
  devOpsSkills: 'DevOps-навыки',
  development: 'Развитие',
  developmentFor: 'Направление развития',
  discipline: 'Дисциплина',
  durationRating: 'Оценка длительности',
  educationInstitution: 'Учебное заведение',
  educationInstitutionOther: 'Другое учебное заведение',
  educationalInterests: 'Образовательные интересы',
  email: 'Email',
  employeeFullName: 'ФИО сотрудника',
  expectationOfEmployer: 'Ожидания работодателя',
  expectationsMatch: 'Соответствие ожиданиям',
  experienceDays: 'Опыт, дней',
  faculty: 'Факультет',
  feedbackDate: 'Дата отзыва',
  filledAt: 'Дата заполнения',
  foreignLanguages: 'Иностранные языки',
  friendAtWork: 'Друг на работе',
  fullName: 'ФИО',
  growthAreas: 'Зоны роста',
  growthAtWork: 'Рост на работе',
  hasJob: 'Есть работа',
  hasRelativesAbroad: 'Есть родственники за границей',
  hobbies: 'Хобби',
  hostRating: 'Оценка ведущего',
  idealEmployer: 'Идеальный работодатель',
  idealWorkplace: 'Идеальное место работы',
  instructionClarity: 'Понятность инструкций',
  internalMeetings: 'Внутренние встречи',
  interviewResult: 'Результат интервью',
  jobContentScore: 'Оценка содержания работы',
  knowledgeApplication: 'Применение знаний',
  knowledgeLevels: 'Уровни знаний',
  leadership: 'Лидерство',
  logic: 'Логика подачи',
  loyalty: 'Лояльность',
  managerCare: 'Забота руководителя',
  materialPerception: 'Восприятие материала',
  materialVolume: 'Объём материала',
  mathematicsExamScore: 'Баллы ЕГЭ по математике',
  meetingDate: 'Дата встречи',
  meetingDynamics: 'Динамика встречи',
  meetingOverall: 'Общая оценка встречи',
  mentor: 'Ментор',
  mentorComment: 'Комментарий ментора',
  mentoringDays: 'Дней менторинга',
  militaryRegistration: 'Воинский учёт',
  missionAndGoal: 'Миссия и цели',
  motivationOfOthers: 'Мотивация других',
  name: 'Название',
  newKnowledge: 'Новые знания',
  organizationalSkills: 'Организационные навыки',
  pace: 'Темп',
  participationGoals: 'Цели участия',
  passedExam: 'Сдавал экзамен',
  passivelySatisfiedComment: 'Комментарий нейтральных',
  personalDataConsent: 'Согласие на обработку данных',
  phone: 'Телефон',
  photo: 'Фото',
  pointOfView: 'Учёт мнения',
  position: 'Позиция',
  practicalSkillsQuality: 'Качество практических навыков',
  practiceHistory: 'История практики',
  professions: 'Профессии',
  programmingSkills: 'Навыки программирования',
  projectTypes: 'Типы проектов',
  projects: 'Проекты',
  projectsInCenter: 'Проекты в центре',
  promotersComment: 'Комментарий сторонников',
  qualityWork: 'Качество работы',
  questionnaireProjects: 'Проекты из анкеты',
  rating: 'Рейтинг',
  recognitionAndPraise: 'Признание и похвала',
  recommendation: 'Рекомендация',
  referrerFullName: 'ФИО рекомендателя',
  registrationRegion: 'Регион регистрации',
  requests: 'Запросы',
  roles: 'Роли',
  russianExamScore: 'Баллы ЕГЭ по русскому',
  safetyScore: 'Оценка безопасности',
  salaryScore: 'Оценка зарплаты',
  saturation: 'Насыщенность',
  selfMotivation: 'Самомотивация',
  skills: 'Навыки',
  source: 'Источник',
  specialty: 'Специальность',
  status: 'Статус',
  submissionNumber: 'Номер заявки',
  surveyDate: 'Дата опроса',
  systemAdministrationSkills: 'Навыки системного администрирования',
  talkAboutSuccesses: 'Обсуждение успехов',
  targetEducation: 'Целевое обучение',
  technicalInterviewDates: 'Даты технических интервью',
  technicalInterviewResults: 'Результаты технических интервью',
  telegram: 'Telegram',
  telegramUrl: 'Ссылка Telegram',
  temporaryRegistration: 'Временная регистрация',
  testingSkills: 'Навыки тестирования',
  theoryHistory: 'История теории',
  thirdExamScore: 'Баллы за третий экзамен',
  thirdExamSubject: 'Третий экзамен',
  toolsAndMaterial: 'Инструменты и материалы',
  topicImportance: 'Важность темы',
  topicRelevance: 'Актуальность темы',
  totalExamScore: 'Сумма баллов ЕГЭ',
  trainer: 'Тренер',
  trainerNameFormula: 'ФИО тренера',
  trainerWork: 'Работа тренера',
  travelAvailability: 'Готовность к командировкам',
  type: 'Тип',
  universityAverageScore: 'Средний балл в вузе',
  universityChoicePrinciple: 'Принцип выбора вуза',
  webDevelopmentSkills: 'Навыки веб-разработки',
  workOrInternship: 'Работа или стажировка',
  workPlanHours: 'План рабочих часов',
  workingConditionsScore: 'Оценка условий труда',
}

export function getFieldLabel(field: FormFieldSchema) {
  return fieldLabels[field.name] ?? field.label
}
